window.UNITS = {'barbarian': {'code': 0,
                            'food': 1,
                            'minTH': 1},
              'archer': {'code': 1,
                        'food': 1,
                        'minTH': 1},
              'giant': {'code': 3,
                        'food': 5,
                        'minTH': 1},
              'goblin': {'code': 2,
                        'food': 1,
                        'minTH': 2},
              'wallbreaker': {'code': 4,
                        'food': 2,
                        'minTH': 3},
              'balloon': {'code': 5,
                        'food': 5,
                        'minTH': 4},
              'wizard': {'code': 6,
                        'food': 4,
                        'minTH': 5},
              'healer':{'code': 7,
                        'food': 14,
                        'minTH': 6},
              'dragon': {'code': 8,
                        'food': 20,
                        'minTH': 7},
              'pekka': {'code': 9,
                        'food': 25,
                        'minTH': 8},
              'babydragon': {'code': 23,
                        'food': 10,
                        'minTH': 9},
              'miner': {'code': 24,
                        'food': 6,
                        'minTH': 10},
              'electrodragon': {'code': 59,
                        'food': 30,
                        'minTH': 11},
              'yeti': {'code': 53,
                        'food': 18,
                        'minTH': 12},
              'dragonrider': {'code': 65,
                            'food': 25,
                            'minTH': 13},
              'minion': {'code': 10,
                        'food': 2,
                        'minTH': 7},
              'hogrider': {'code': 11,
                        'food': 5,
                        'minTH': 7},
              'valkyrie': {'code': 12,
                        'food': 8,
                        'minTH': 8},
              'golem': {'code': 13,
                        'food': 30,
                        'minTH': 8},
              'witch': {'code': 15,
                        'food': 12,
                        'minTH': 9},
              'lavahound': {'code': 17,
                        'food': 30,
                        'minTH': 9},
              'bowler': {'code': 22,
                        'food': 6,
                        'minTH': 10},
              'icegolem': {'code': 58,
                        'food': 15,
                        'minTH': 11},
              'headhunter': {'code': 82,
                        'food': 6,
                        'minTH': 12}
};
window.SUPERUNITS = {'barbarian': {'code': 26,
                                'food': 5,
                                'minTH': 11},
                  'archer': {'code': 27,
                            'food': 12,
                            'minTH': 11},
                  'giant': {'code': 29,
                            'food': 10,
                            'minTH': 12},
                  'goblin': {'code': 55,
                            'food': 3,
                            'minTH': 11},
                  'wallbreaker': {'code': 28,
                            'food': 8,
                            'minTH': 11},
                  'balloon': {'code': 57,
                            'food': 8,
                            'minTH': 12},
                  'wizard': {'code': 83,
                            'food': 10,
                            'minTH': 12},
                  'infernodragon': {'code': 63,
                            'food': 15,
                            'minTH': 12},
                  'minion': {'code': 84,
                            'food': 12,
                            'minTH': 12},
                  'valkyrie': {'code': 64,
                            'food': 20,
                            'minTH': 12},
                  'witch': {'code': 66,
                            'food': 40,
                            'minTH': 12},
                  'icehound': {'code': 76,
                            'food': 40,
                            'minTH': 12},
                  'dragon': {'code': 81,
                            'food': 40,
                            'minTH': 12},
                  'bowler': {'code': 80,
                            'food': 30,
                            'minTH': 12}
};
window.SPELLS = {'lightning': {'code': 0,
                            'food': 1,
                            'minTH': 5},
                'healing': {'code': 1,
                          'food': 2,
                          'minTH': 6},
                'rage': {'code': 2,
                          'food': 2,
                          'minTH': 7},
                'jump': {'code': 3,
                          'food': 2,
                          'minTH': 9},
                'freeze': {'code': 5,
                          'food': 1,
                          'minTH': 9},
                'clone': {'code': 16,
                          'food': 3,
                          'minTH': 10},
                'invisibility': {'code': 35,
                              'food': 1,
                              'minTH': 11},
                'poison': {'code': 9,
                          'food': 1,
                          'minTH': 8},
                'earthquake': {'code': 10,
                          'food': 1,
                          'minTH': 8},
                'haste': {'code': 11,
                          'food': 1,
                          'minTH': 9},
                'skeleton': {'code': 17,
                          'food': 1,
                          'minTH': 9},
                'bat': {'code': 28,
                        'food': 1,
                        'minTH': 10}
};
window.SIEGEMACHINES = {'wallwrecker': {'code': 51,
                                    'food': 1,
                                    'minTH': 12},
                      'battleblimp': {'code': 52,
                                    'food': 1,
                                    'minTH': 12},
                      'stoneslammer': {'code': 62,
                                    'food': 1,
                                    'minTH': 12},
                      'siegebarracks': {'code': 75,
                                    'food': 1,
                                    'minTH': 13},
                      'loglauncher': {'code': 87,
                                    'food': 1,
                                    'minTH': 13},
                      'flameflinger': {'code': 0,
                                    'food': 1,
                                    'minTH': 14}
};
